### ISSUE TITLE
React-Router with Carousel

### ISSUE THREAD

**Issue by pnitto** [FormidableLabs/nuka-carousel#35] opened 2015-10-31 23:29 UTC
I have been trying to set up my carousel with links to another page but it looks like the carousel obliterates  my react-router links. Is this possible to do?

**Comment by aij** [comment] 2016-06-29 19:59
FWIW, I'm using <Link> from react-router inside the carousel and it works fine...

**Comment by zuizuihao** [comment] 2016-08-22 07:22
+1

**Comment by ashika01** [comment] 2018-09-13 21:00
Closing the issue because it can not be reproduced in newer version(4.3.10). Please reopen if you still experience this issue with the latest stable version.

Thank you.

**Closed by ashika01** 2018-09-13 21:00 UTC
