### ISSUE TITLE
Lag while swiping on wrapAround

### ISSUE THREAD

**Issue by jibin2706** [FormidableLabs/nuka-carousel#612] opened 2019-11-10 14:23 UTC
The issue only exist on wrapAround. Is there any workaround this?
https://codesandbox.io/s/nuka-carousel-bug-sx9j6

**Comment by artemtam** [comment] 2019-11-15 16:08
Spent 2 hours trying to debug this. Realised that the code is shitty and unmaintainable, so you'd rather use another library. I'm angry and depressed. @sarmeyer you're responsible for my mental health now.

**Comment by artemtam** [comment] 2019-11-15 16:09
😡

**Comment by Saikava** [comment] 2019-12-19 08:00
There is open issue for this bug #494

**Comment by sarmeyer** [comment] 2020-01-07 18:29
@jibin2706 thanks for sending a codesandbox! Unfortunately, I am not able to reproduce any issue in the sandbox. I know other folks have had issues with the "wraparound flash" so in favor of #494 I'll close this issue. You can follow along there if you're still having issues

**Closed by sarmeyer** 2020-01-07 18:29 UTC
