### ISSUE TITLE
Supported react version

### ISSUE THREAD

**Issue by Luis-Palacios** [FormidableLabs/nuka-carousel#678] opened 2020-03-17 21:00 UTC
# Bugs and Questions

- [x] I've searched open [issues](https://github.com/FormidableLabs/nuka-carousel/issues) to make sure I'm not opening a duplicate issue
- [x] I have read through the docs before asking a question
- [x] I am using the latest version of nuka-carousel

### Describe Your Environment

- What version of nuka-carousel are you using?
4.6.6
- What version of React are you using?
15.3.1
- What browser are you using?
Chrome
- What machine are you on?
MacBook Pro (16-inch 2019), Catalina 10.15.3

### Describe the Problem

Hello,

I might be wrong here but according to the package.json peer dependencies: ` "react": "^0.14.9 || ^15.3.0 || ^16.0.0",` my current react version (15.3.1) is supported on the latest nuka-carousel version (4.6.6) but when I try to upgrade the slides no longer appear.

Is there any place where I could see and confirm the minimum supported react version?  looking at the peer dependencies on the package.json file gives me hope that my good old react version is supported   but I'm not sure if this alone means my react version is supported:

Anyway, I have created a clone of the demo sandbox but using my react version and you can see that the slides don't appear [Code Sandbox Demo](https://codesandbox.io/s/bold-shape-8i2os). Looking through the GitHub issues I found this one [Slides sometimes render with zero height](https://github.com/FormidableLabs/nuka-carousel/issues/103) so I try that workaround, so you should see that code currently commented. But after inspecting the DOM I realize that is not a zero height issue but instead the slide themself are not being rendered.

If it is of any help I have verified that the version where everything works correctly for me is on 4.4.4, after that version I start running into different issues.

**Expected behavior:** Slides Render
**Actual behavior:** Slides doesn't render

**Comment by venwidh** [comment] 2020-11-27 08:43
Same issue here with React 16.14.0.

Just like mentioned above, everything is fine if using version 4.4.4.
looking on the Changelogs of 4.4.5 maybe it is because of this?

> #673 Remove deprecated UNSAFE_componentWillReceiveProps

**Comment by irodger** [comment] 2021-05-13 00:32
The same warning with react 17+

**Comment by ValGeorgiev** [comment] 2022-03-27 16:35
Hey @Luis-Palacios, I cannot reproduce this anymore with v5. Could you try again and let me know if there is still an issue, please? I will close this for now. Feel free to reopen it

**Closed by ValGeorgiev** 2022-03-27 16:35 UTC
Labels: Verified, v5
