### ISSUE TITLE
Externally controlled carousel not animating on first click

### ISSUE THREAD

**Issue by lukebennett88** [FormidableLabs/nuka-carousel#688] opened 2020-04-21 06:02 UTC
# Bugs and Questions

I'm trying to build a carousel is externally controlled.

For some reason the first time I click the prev or next button it doesn't animate. It works for every slide after that.

Am I doing something wrong or is this a bug?

I've created an MVP on CodeSandbox: 
https://codesandbox.io/s/externally-controlled-nuka-carousel-6uktz?file=/src/App.js

**Comment by audreybo** [comment] 2020-04-28 07:47
I've had the same issue appearing when I upgraded the carousel I use in a project. It seems to have appeared from version 4.6.5, so I downgraded to 4.6.4.

**Comment by lukebennett88** [comment] 2020-04-29 01:14
Oh, awesome. Glad it's not just me. I tried the same thing and it fixed the bug.

**Comment by sarmeyer** [comment] 2020-05-20 23:06
Hey @lukebennett88 thanks for submitting this bug! and @audreybo thanks for that info - I'll take a look into which of the changes we made in 4.6.5 might have resulted in this behavior. One of those changes was removing `componentWillReceiveProps` and I have a hunch that's where we will find the issue

**Comment by sarmeyer** [comment] 2020-05-20 23:32
This bug was actually introduced in this PR https://github.com/FormidableLabs/nuka-carousel/pull/490/

I will work on a way to satisfy both this issue and the one that prompted that fix

**Comment by michielmetcake** [comment] 2020-10-12 11:58
Any update on this issue?

**Comment by michielmetcake** [comment] 2020-10-12 12:08
Found an fix for our issue. Providing a `easing` prop did solve the issue.

**Comment by ValGeorgiev** [comment] 2022-03-27 16:53
Hey all, I cannot reproduce this issue with the latest version v5.0.7. I will close this issue for now, please feel free to reopen it if the issue is still reproducible. You can test it [here](https://nuka-carousel-next.vercel.app/)

**Closed by ValGeorgiev** 2022-03-27 16:53 UTC
