### ISSUE TITLE
Vertical Scroll Not Handled in IOS Chrome

### ISSUE THREAD

**Issue by DWMiller** [FormidableLabs/nuka-carousel#385] opened 2018-07-23 17:33 UTC
Meaning, if your drag/swipe isn't perfectly horizontal, your scroll will adjust with the vertical drag. 

Haven't managed to confirm why this is, anyone have any insights or able to confirm it's not just something else on my end?

**Comment by bnhovde** [comment] 2018-08-08 13:42
Having the same issue. This effectively means the user will get stuck on the carousel on all devices with touch.

**Comment by bnhovde** [comment] 2018-08-08 14:04
Found the culprit. it's the `touch-action: none` style applied to the `<ul class="slider-list">...</ul>`

A temporary hack:
```
  .slider-list {
    touch-action: initial !important;
  }
```

**Comment by DWMiller** [comment] 2018-08-08 15:04
hmm, I don't see a touch-action: none on that element, but touch-action: pan-y pinch-zoom.

**Comment by bnhovde** [comment] 2018-08-09 09:34
@DWMiller - Hmm, I was on version `4.2.5`. I updated to `4.3.5` and that resolved the above. What version are you on?

@ryan-roemer PS: After updating to the latest version the above issue seems to be resolved.

**Comment by DWMiller** [comment] 2018-08-09 14:00
@bnhovde `4.3.2` here,  I'll give it a bump and check back.

**Comment by sarmeyer** [comment] 2018-08-31 19:52
@DWMiller did upgrading fix the issue you were seeing?

**Comment by DWMiller** [comment] 2018-10-19 19:05
Sorry for the lack of follow up here, and no, this issue was not resolved. 

I'm also able to reproduce the problem on http://kenwheeler.github.io/nuka-carousel. I'm aware that that is an older version, but same issue.

Anyone have any links to sites using this I could compare to? (I'd also test the demo in the repo itself, but installing it on windows seems to be a no go)

**Comment by ScottSmith95** [comment] 2019-01-25 22:30
I can confirm that @bnhovde's solution works. This is related to https://github.com/FormidableLabs/nuka-carousel/issues/447, in my opinion.

**Comment by missmimia** [comment] 2019-05-23 08:14
> @DWMiller - Hmm, I was on version `4.2.5`. I updated to `4.3.5` and that resolved the above. What version are you on?
> 
> @ryan-roemer PS: After updating to the latest version the above issue seems to be resolved.

meet the same thing...

set the style you said, but it doesn't work.

my version is "nuka-carousel": "^4.4.3", IOS safari.

**Comment by sarmeyer** [comment] 2019-12-02 21:26
fixed in #609

**Closed by sarmeyer** 2019-12-02 21:26 UTC
Labels: investigate, verified
