### ISSUE TITLE
Slides sometimes render with zero height

### ISSUE THREAD

**Issue by aczerepinski** [FormidableLabs/nuka-carousel#103] opened 2016-06-14 18:38 UTC
I'm testing out 2.0.0 via the master branch, and seeing a new issue where slides will sometimes render with zero height. This is unrelated to/not fixed by commit 5ed9ff5. Resizing my browser window adds height to the slides instantly. I added this code to setDimensions, which fixes it for the most part:

```
if (firstSlide.offsetHeight === 0) {
   var width = window.innerWidth;
   firstSlide.style.width = width + 'px';
   firstSlide.style.height = (width/2.4) + 'px'; //known ratio for my images - needed for Safari
}
```

I'm not submitting this as a PR right now because it feels a bit hacky and istied to my external CSS and image ratio. Is anyone else experiencing this? Is there a cleaner solution?

This isn't an issue on ^1.2.0.

**Comment by kenwheeler** [comment] 2016-06-15 01:26
It's probably the absolute positioning... Necessary for wrapAround, I didn't want to do it, but people need it so I did. What's your fix look like generally? Would love to undo any damage done, sooner than later.

**Comment by aczerepinski** [comment] 2016-06-15 13:31
Sorry - after further testing, the fix I was working on probably isn't the right direction. It does force the slides to have height, but introduces other drawbacks such as slide transition hiccups.  It I'll try to find something cleaner that I can contribute back, but in the meantime I may need to cherry pick the autoplay code into 1.2 without wrapAround. I might wrap by calling `goToSlide(0)`, and leave the CSS alone.

Also, I'm using plenty of my own CSS, external controllers, etc. If nobody else is chiming in with "me too" perhaps this is just a CSS conflict that won't effect everyone. Feel free to close.

**Comment by lizlove** [comment] 2016-06-16 23:16
I'm having the same issue with slides rendering with zero height and resizing the browser adds height to the slides instantly as well. I removed all applicable css.  Currently if I set an initialSlideHeight in pixels it will avoid the blank slideshow, but my slides then do not size to the frame (instead overlap, etc). Is there a way to avoid the zero state without compromising the scaling? 
Thanks!

**Comment by Godefroy** [comment] 2016-06-24 14:46
Same issue here.

1. First load: Height=0, I think it's because the carousel adjust its height when images are not yet loaded.
2. Resize browser: Perfect.
3. Resize again: Width ok, Height not ok (stay the same than after first resize)
4. Second load (remove and add component again without refreshing the page): Perfect.

So there are two problems: size detection on load, and browser resize.

**Comment by alexanderfrey** [comment] 2016-06-28 17:24
Same problem here for the 2.0.2

**Comment by kenwheeler** [comment] 2016-06-29 00:04
So how should this work? For wraparound to work right, I need to absolutely position, which kills height layout. So I set it to the height of the first slide. What's the ideal fix here?

**Comment by Godefroy** [comment] 2016-06-29 09:39
Maybe you could detect image onload event (browser compatibilité is not easy in this case...) to resize carousel.

**Comment by aczerepinski** [comment] 2016-06-29 12:01
I may not understand the desired UX of wraparound. A simple solution would be: if someone calls nextSlide and you're already at the last slide, go to the first slide instead. That doesn't require absolute positioning and works for my needs. Is the CSS change done so that slide transitions always animate in the same direction?

**Comment by kenwheeler** [comment] 2016-06-29 12:27
Wraparound mode is where you never hit the end. Whether you hit next, or swipe, it loops. Not an easy problem to solve. In the past I've done it with clones, but that introduces a whole slew of new issues. With absolute positioning, I can move slides from the back to front when needed.

**Comment by stefangordon** [comment] 2016-06-29 17:59
Something as simple as running `window.dispatchEvent(new Event('resize'));`  after your slides are loaded fixes the issue, as it causes you to rerun `setDimensions(...)`  (this is my current workaround).    Likely finding a way to call part of `setDimensions` on `componentDidUpdate()` would help in many cases (you can't just do this directly, as set dimensions changes state at the moment so you'd end up in a loop, but I'm sure the relevant bits could be executed).

**Comment by gablabelle** [comment] 2016-07-19 15:02
Having the same problem.

Used the following in parent component holding the Carousel component in order to make it work:

```
  componentDidMount() {
    setTimeout(() => {
      window.dispatchEvent(new Event('resize'));
    }, 0);
  },
```

Any better suggestions would be appreciated. Thanks.

**Comment by firdausious** [comment] 2016-07-20 04:46
@gablabelle nice solution.. would be nice to put it on the carousel itself

**Comment by gablabelle** [comment] 2016-08-05 14:27
Actually a much better solution is to use onLoad on the img.

`<img src={image} onLoad={this._handleImageLoaded} className="top-presentation-image" alt="" />`

and _handleImageLoaded would trigger the event.

**Comment by w3apps** [comment] 2016-08-10 08:21
+1

**Comment by KjellConnelly** [comment] 2016-08-18 02:30
Thanks everyone for figuring this out for me. Here's the solution with inline javascript so you don't need to write another function somewhere else:

`                <img src={image} onLoad={() => {window.dispatchEvent(new Event('resize'));}} />
`

**Comment by gablabelle** [comment] 2016-08-18 14:15
@KjellConnelly Let's simply remember people that this constructor is supported in most modern browsers (with Internet Explorer being the exception). For a more verbose approach (which works with Internet Explorer), see the [old-fashioned](https://developer.mozilla.org/en-US/docs/Web/Guide/Events/Creating_and_triggering_events#The_old-fashioned_way) (MDN docs).

**Comment by apkoponen** [comment] 2016-09-11 12:13
I'm not 100% sure what was causing this for me. I was using a "CSS-hack" `padding-bottom: 56.25%;` to set the aspect ratio of the slides (style was set with Radium). I would suspect that the problem had something to do with the order the width is set and slide height is calculated as the height is 0 as long as the slide width is 0.

I solved my problem by creating a simple higher order component that just sets a ref for the carousel and calls setDimensions() on the carousel as soon as the component gets mounted (setTimeout with 0ms is used to make sure all rendering that is in progress gets done before we reset the dimensions).

```
import React, { Component } from 'react';
import Carousel from 'nuka-carousel';

class Slider extends Component {
  componentDidMount() {
    setTimeout(() => {
      this.refs.carousel.setDimensions();
    }, 0);
  }

  render() {
    return (
      <Carousel
        ref="carousel"
        {...this.props}
      />
    );
  }
}

export default Slider;
```

**Comment by YovkaHan** [comment] 2016-09-16 20:54
window.dispatchEvent works only on modern browsers. On  IE 11 , Safari 5 it didn't work

**Comment by gablabelle** [comment] 2016-09-19 16:24
@YovkaHan Like I said check out the [old fashion way](https://developer.mozilla.org/en-US/docs/Web/Guide/Events/Creating_and_triggering_events#The_old-fashioned_way) then.

**Comment by homs44** [comment] 2017-01-05 14:51
how about you use setState in onLoad ?? 
set any data to some variable  then render is occur
I think it is better then use dispatchEvent because of old version of other browsers,

**Comment by chinnawatp** [comment] 2017-01-23 09:47
Anyone working on this issue?

I tried to use  'window.dispatchEvent' hack, but it still shows cutoff carousel for a few sec.

**Comment by edwardaa** [comment] 2017-05-16 08:10
If the images have fixed a height, just set a height value:
```html
<img src={image.url} alt={image.alt} key={index} style={{height: '100px'}} />
```

If the images have a fixed ratio and fill full width of the viewport, just set a height ratio (e.g.,4:3):
```html
<img src={image.url} alt={image.alt} key={index} style={{height: '75vw'}} />
```

**Comment by dbo** [comment] 2017-05-17 13:46
This workaround works for me: Waiting for `onLoad` of the first image, calling `setDimensions` on the mounted carousel component.

**Comment by kristojorg** [comment] 2017-05-25 23:39
This isn't working for me, I'm seeing height set to 0 in Safari even after this workaround and trying resizing the window. Any suggestions?

**Comment by tudoanh** [comment] 2017-10-24 03:21
@KjellConnelly Thanks a lot, work like a charm to me.

**Comment by andreafdaf** [comment] 2017-11-01 20:59
Expanding a bit on @KjellConnelly following what @gablabelle said about browser compatibility I did the following:
- somewhere in the code (I usually have an "utils" file with helper functions that get reused around the project)
```javascript
export const triggerEvent = (target, type) => {
  const doc = window.document;
  if (doc.createEvent) {
    const event = doc.createEvent('HTMLEvents');
    event.initEvent(type, true, true);
    target.dispatchEvent(event);
  } else {
    const event = doc.createEventObject();
    target.fireEvent(`on${type}`, event);
  }
};
```
- when using the carousel:
```javascript
import { triggerEvent } from 'utils';
...
<img src={image} onLoad={() => triggerEvent(window, 'resize')} />
```

Thanks to this gist https://gist.github.com/dciccale/6226151 for the cross-browser triggerEvent

**Comment by ryan-roemer** [comment] 2018-03-10 21:14
Is this still an issue on `nuka-carousel@3.1.0+` now that we've landed https://github.com/FormidableLabs/nuka-carousel/pull/291?

**Comment by TheMaverickProgrammer** [comment] 2018-04-15 15:02
This issue is still present in the latest build. I used @gablabelle's solution in the `componentDidUpdate()` method of my class and it worked like a charm. why is this not resolved?

**Comment by ryan-roemer** [comment] 2018-04-15 15:07
The lib has changed drastically from the opening of this issue. PRs welcome!

**Comment by tol-is** [comment] 2018-07-05 13:52
I had a similar issue, where I was listening to a resize event to reposition the carousel container. I didn't have an issue with the contents of the slides, because i'm wrapping each slide to a fixe ratio container, but the slider-frame would not always resize correctly. @gablabelle's solution worked well for me.

**Comment by samwhale** [comment] 2018-07-05 20:21
@TheMaverickProgrammer Can you provide us a minimal repo with install and error reproduction steps so that we can see the bug?

**Comment by TheMaverickProgrammer** [comment] 2018-07-05 20:32
@samwhale are you paying me?

**Comment by samwhale** [comment] 2018-07-05 20:38
@TheMaverickProgrammer Sorry, I won't be paying you.

You said the bug is still present and I'd like to verify that. If you could, please make a minimal repo displaying the problem. That would be the most helpful so that we can get this ironed out quickly.

If anybody could provide a minimal repo with error reproduction steps that would be very helpful.

**Comment by TheMaverickProgrammer** [comment] 2018-07-06 00:29
It's the same problem as everyone elses.

**Comment by ryan-roemer** [comment] 2018-07-06 00:46
Thanks for the confirmation of the issue.

As we have two folks right now with a small allocation of time to work on `nuka-carousel`, we're relying on the community to get us a minimal reproduction with install + error reproduction steps (or an open PR with just a failing regression test) to allow us to prioritize _this_ particular issue. And we likely can get it fixed if we have the reproduction to kickstart us / ensure that we're working on a **real** issue 😄 

And no worries, if folks don't have time right now -- we'll leave this issue in open state and work on other `nuka-carousel` issue and perhaps catch this one the next time around!

**Comment by robinsandborg** [comment] 2018-10-09 14:14
I’m having this issue as well, but when I moved my slider code to a new project in order to create a minimal example, the issue does not present itself.

Seems like this one might be hard for you guys to reproduce!

**Comment by sarmeyer** [comment] 2018-12-21 00:04
fixed with #469

**Closed by sarmeyer** 2018-12-21 00:04 UTC
Labels: unverified

**Comment by fivetwelve** [comment] 2019-02-15 00:43
I wanted to add a comment and resolution for anyone experiencing a similar situation to mine. I was seeing this problem not on initial load but when I would click on a link to another page and then go back to the initial page (which has then been cached): the carousel would then have a zero height.

Unfortunately, I was using this with Gatsby and because it needs to be SSR it couldn't easily use a window event. My slide images were also loaded as background-image elements to cause another wrinkle. Note that my slides just had to follow a common aspect ratio so I was able to use height: 42vw (anamorphic wide ratio for me, change to suit yours) on my carousel and it seemed to resolve. 

Thanks to @edwardaa in an earlier comment to spark this fix.

**Comment by AllanPooley** [comment] 2019-02-17 02:06
@fivetwelve I'm also using nuka-carousel with Gatsby. @apkoponen's solution worked for me. Had to update it due to changes to React:

```
class CarouselComponent extends Component {

  componentDidMount() {
    setTimeout(() => {
      this.carousel.setDimensions();
    }, 0);
  }

  render() {
    const {
      slides
    } = this.props;
    return (
      <section className="my-carousel">
        <div className="slides">
          <Carousel
            ref={(carousel) => { this.carousel = carousel; }}
          >
             // Map over slides
          </Carousel>
       </div>
     </section>
     );
  }
}
