### ISSUE TITLE
afterSlide Hook Not Firing in Version 4.3.6

### ISSUE THREAD

**Issue by daveyjones** [FormidableLabs/nuka-carousel#400] opened 2018-08-17 02:21 UTC
The code below adds the class "current" to the current slide. However, the `afterSlide` hook doesn't seem to be firing in 4.3.6. When downgrading to version 4.3.5, the following code works as expected. It's very possible I'm doing something wrong but since it works in 4.3.5 I thought I'd report it in case it helps resolve an underlying issue related to the `afterSlide` hook.

```
<Carousel afterSlide={current_slide => {this.setState({current_slide: current_slide})}}>
    {this.state.destinations.map((props, i) => {
        return (
            <img src={props.image} className={this.state.current_slide === i ? "current" : ""} />
        )
    })}
</Carousel>
```

**Comment by ryan-roemer** [comment] 2018-08-17 03:41
Is this something that you could capture in a failing regression test and open a PR with just the failure for us to work against? Would be an amazing way to kickstart the work for us on our end!

If not, we'd also super appreciate a minimal repository with install + error reproduction steps to let us . clone something and see the problem in action... (looks like you're already started with the above example...)

Thanks!!!

**Comment by DWMiller** [comment] 2018-08-17 12:31
Same issue. 

Unless I'm misunderstanding it the problem is this:

https://github.com/FormidableLabs/nuka-carousel/commit/14ee29fade010a58c730128dfa2f96df2b2d1424

    if (index !== this.state.currentSlide) {
      this.props.afterSlide(index);
    }

This is occuring in the callback of a setState. In that setState, currentSlide is updated to equal index, and the since the callback uses the updated state, it's comparing the current index to the current index, rather than the previous, so it's always equal (unless you change slides again faster than the timeout)

**Comment by sarmeyer** [comment] 2018-09-06 02:56
fixed in https://github.com/FormidableLabs/nuka-carousel/pull/403 - release v4.3.8

**Closed by sarmeyer** 2018-09-06 02:56 UTC
Labels: unverified
