### ISSUE TITLE
translate3d with half pixel values causes blurry text in carousel

### ISSUE THREAD

**Issue by lauriejones** [FormidableLabs/nuka-carousel#82] opened 2016-04-19 23:12 UTC
At certain (odd) pixel screen widths the translate left position gets a half pixel value.

e.g. `transform: translate3d(-325.5px, 0px, 0px);`

This causes all text within the carousel to be blurry. Can this value be rounded to a whole number?

`this.getTweeningValue('left')` => `Math.round(this.getTweeningValue('left'))`

**Comment by peteroid** [comment] 2016-07-14 19:45
Not sure if this is related my issue #127

**Comment by sarmeyer** [comment] 2020-01-12 01:42
Hi @lauriejones - I'm going to close this issue as I don't believe it's applicable anymore with the updates that have been made to the carousel since 2016. If it is indeed still an issue for you, please reopen this issue and if possible, include steps to reproduce or a sandbox example. Thanks!

**Closed by sarmeyer** 2020-01-12 01:42 UTC
