### ISSUE TITLE
Prev slide appears after a delay when wrapAround={true}

### ISSUE THREAD

**Issue by psin81** [FormidableLabs/nuka-carousel#755] opened 2021-02-11 16:35 UTC
# Bugs and Questions

### Describe Your Environment

- What version of nuka-carousel are you using?
  4.7.5
- What version of React are you using?
- 17.0.1
- What browser are you using?
- Chrome/Safari
- What machine are you on?
Macbook Pro
### Describe the Problem
When wrapAround is set to true then the previous slides take time to appear in the dom. I have my carousel config and gif for the issue I'm facing below. The delay isn't consistent so the behaviour isn't smooth.
Anyone else facing the same issue or has a short term fix?

**Expected behavior:** [What you expect to happen]
**Actual behavior:** [What actually happens]
![ezgif com-gif-maker](https://user-images.githubusercontent.com/21307538/107671042-4b07fa00-6c8b-11eb-8b88-43fdd6abb6db.gif)

 ```
const [showPrevButton, setPrevButtonStatus] = useState(false)

 <Carousel
heightMode="max"
          initialSlideHeight={364}
          initialSlideWidth={100}
          slidesToScroll={1}
          renderBottomCenterControls={null}
          cellSpacing={10}
          disableEdgeSwiping
          wrapAround
          slideWidth="232px"
          renderCenterRightControls={({ nextSlide }) => (
            <IconButton onClick={nextSlide} >
              <ArrowForward />
            </IconButton>
          )}
          {...(!showPrevButton
            ? {
                renderCenterLeftControls: null,
                afterSlide: () => setPrevButtonStatus(true)
              }
            : {
                renderCenterLeftControls: ({ previousSlide }) => (
                  <IconButton onClick={previousSlide} >
                    <ArrowBack />
                  </IconButton>
                )
              })}
              >
```
### Additional Information
Any additional information, configuration or data that might be necessary to reproduce the issue.

**Comment by ayozemr** [comment] 2021-02-27 20:26
Also seein this, any fix?

**Comment by carlosmori** [comment] 2021-03-09 21:00
Me too, trying to find a workaround to it but it seems hard

**Comment by babsonmatt** [comment] 2021-03-09 21:25
Looks like this has something to do with waiting for the scroll animation to complete - `disableAnimation: true` eliminates the issue

**Comment by ValGeorgiev** [comment] 2021-11-25 10:04
Hey @psin81 , thanks for submitting this issue and sorry for the late response. I tried to reproduce it  with the latest version but I am not able to. Can someone else confirm that this is fixed as well?

**Comment by clmcdonald** [comment] 2021-12-13 20:27
@ValGeorgiev I have reproduced the same exact issue except it is the forward button instead of the previous button. Reproduction is here: https://github.com/clmcdonald/nuka-carousel-bug-reproduction

**Comment by ValGeorgiev** [comment] 2021-12-13 21:22
@clmcdonald I can reproduce it as well. Thanks for letting us know. This will be fixed in the new version v5. A little bit of context: Currently the slides are absolute positioned and the animation is impossible to be smooth because there are only 3 elements in the dom, so we are moving them when you go next/prev. Thats why we see this flickering. We are rewriting the whole library with typescript and such issues as this are with the highest priority at the moment.

**Comment by ValGeorgiev** [comment] 2022-02-17 13:26
Hi all, this issue should be fixed in v5. [Link with example](https://nuka-carousel.vercel.app/?slides=6&params=%7B%22wrapAround%22:true,%22slidesToShow%22:3%7D). I will close it for now, please feel free to raise other issue if you can still reproduce it.

**Closed by ValGeorgiev** 2022-02-17 13:26 UTC
Labels: v5
