### ISSUE TITLE
slides blink or flash on wrapAround

### ISSUE THREAD

**Issue by ethanryan** [FormidableLabs/nuka-carousel#502] opened 2019-02-11 04:00 UTC
# Bugs and Questions

When wrapAround={true} and clicking on previous from first slide, or next from last slide, the new active slide blinks or flashes.

![gif example of blinking slide](https://media.giphy.com/media/Ylm6WnuQghOsjRq6UA/giphy.gif)

This issue has been addressed before, [and appears to have been fixed in pr 367](https://github.com/FormidableLabs/nuka-carousel/pull/367), but I am experiencing the exact buggy behavior referenced there, in "Bug/wrap around slide flash".

my code: 

```
import React from "react";
import Carousel from "nuka-carousel";

export default class extends React.Component {
  render() {
    return (
      <Carousel wrapAround={true}>
        <img
          src="http://placehold.it/1000x400/ffffff/c0392b/&text=slide1"
          alt=""
        />
        <img
          src="http://placehold.it/1000x400/ffffff/c0392b/&text=slide2"
          alt=""
        />
        <img
          src="http://placehold.it/1000x400/ffffff/c0392b/&text=slide3"
          alt=""
        />
        <img
          src="http://placehold.it/1000x400/ffffff/c0392b/&text=slide4"
          alt=""
        />
        <img
          src="http://placehold.it/1000x400/ffffff/c0392b/&text=slide5"
          alt=""
        />
        <img
          src="http://placehold.it/1000x400/ffffff/c0392b/&text=slide6"
          alt=""
        />
      </Carousel>
    );
  }
}
```

The above component is rendered in an AppContainer component, that has a styled component with the following css:

```
const AppContainerWrapper = styled.div`
  background: limegreen;
  border: 1px solid black;
  margin: 20px;
`;
```

The `limegreen` is to make the blink or flash more apparent.

### Prerequisites

**Feel free to delete this section if you have checked off all of the following.**

- [x] I've searched open [issues](https://github.com/FormidableLabs/nuka-carousel/issues) to make sure I'm not opening a duplicate issue
- [x] I have read through the docs before asking a question
- [x] I am using the latest version of nuka-carousel

### Describe Your Environment

- What version of nuka-carousel are you using? **4.4.7**
- What version of React are you using? **16.8.1**
- What browser are you using? **Chrome**
- What machine are you on? **MacBook Air**

### Describe the Problem

It's easier to show us than tell us what's going wrong with your code. Because of this, we ask that you do one of three things to help us reproduce the bug:

1. Create a public minimal repository that we can `git clone`, with install + error reproduction steps in the README.
https://github.com/ethanryan/test-carousel

2. Create a sandbox, reproduce your issue in the code, and paste the link here.
3. Open up a PR, include "WIP" and the Issue # in the title, and point us to the failing regression tests.

**Expected behavior:** [What you expect to happen] no slide blinks or flashes when wrapAround={true} and clicking on previous from first slide, or next from last slide

**Actual behavior:** [What actually happens] the last slide or first slide is blinking

### Additional Information
Any additional information, configuration or data that might be necessary to reproduce the issue.

**Comment by AllanPooley** [comment] 2019-02-14 23:50
Can confirm @ethanryan's issue, experiencing the same on my end.

* What version of nuka-carousel are you using? **nuka-carousel@4.4.8**
* What version of React are you using? **16.5.2**
* What browser are you using? **Chrome**
* What machine are you on? **MacBook Pro**

@mariano-formidable

**Comment by inergy** [comment] 2019-02-15 21:27
duplicate of https://github.com/FormidableLabs/nuka-carousel/issues/494

**Comment by sarmeyer** [comment] 2019-03-04 17:43
fixed in https://github.com/FormidableLabs/nuka-carousel/pull/508

**Closed by sarmeyer** 2019-03-04 17:43 UTC
