### ISSUE TITLE
Slide Height

### ISSUE THREAD

**Issue by nmkim8** [FormidableLabs/nuka-carousel#18] opened 2015-07-31 21:03 UTC
It seems like as if the height of the slide is the height of the largest slide. Is there a way to specify the slide's height? Or an option in props we can set so all of the slides conform to the height of its contents? Otherwise, I'd like to request such an option.

**Comment by Zetberg** [comment] 2015-10-30 18:29
+1

**Comment by truca** [comment] 2015-11-16 19:45
+1

**Comment by Martin-zhz1994** [comment] 2015-12-09 11:14
+1

**Comment by cheeks** [comment] 2016-01-21 17:28
+1

**Comment by kenwheeler** [comment] 2016-01-21 17:41
How would you want this to work, exactly?

**Comment by cheeks** [comment] 2016-01-21 22:54
Currently the whole carousel has the height of its tallest slide. If there was a prop called fixedHeight, that would be `true`. For those who want there to be a variable height, something like `<Carousel fixedHeight={false}>`?

**Comment by Zetberg** [comment] 2016-03-23 15:15
The issue is if you have items in carousel with different heights, than because of height of its tallest child, there is huge gap between smallest and largest child, fixedHeight prop would be nice, but all we need is to set carousel height based on current slide, not tallest one

**Comment by benjaminmiles** [comment] 2016-04-20 13:50
+1

**Comment by xdroidx** [comment] 2016-04-26 14:22
+1. It should work like wrote @Zetberg

**Comment by nileshbhosale** [comment] 2016-06-23 14:33
+1

**Comment by prrraveen** [comment] 2016-07-12 13:54
+1

**Comment by vijoditz-agustin** [comment] 2016-07-31 19:40
+1

**Comment by vijoditz-agustin** [comment] 2016-07-31 20:48
+1
Current not-so-pretty solution:
```javascript
afterSlide (currentSlide) {
	const list = window.document.querySelector('.slider-list');
	const nextSlide = list.childNodes[currentSlide];
	list.style.height = nextSlide.offsetHeight + 'px';
}
render() {
 ...
 <Carousel decorators={decorators} afterSlide={this.afterSlide}>
 ...
}
```

**Comment by upq** [comment] 2016-11-20 11:31
no news here? @kenwheeler

**Comment by kenwheeler** [comment] 2016-11-21 18:33
@mdaxtman

**Comment by mdaxtman** [comment] 2016-11-22 08:06
I'll get to work on this tomorrow. I'm working on all the backlogged issues, and the high amount of activity has put this on the top of the list.

**Comment by ryan-roemer** [comment] 2018-03-10 21:14
Is this still an issue on `nuka-carousel@3.1.0+` now that we've landed https://github.com/FormidableLabs/nuka-carousel/pull/291?

**Comment by tgg-praveengupta** [comment] 2018-04-05 04:13
@vijoditz-agustin , thankyou for the solution , it did the part but i am having issue on 1 slide/component as it has dropdown in it. Solution?

**Comment by sarmeyer** [comment] 2018-09-04 16:58
@tgg-praveengupta Can you provide an example of the component as you're using it with a dropdown? I haven't been able to reproduce this.

**Comment by sarmeyer** [comment] 2018-09-07 16:07
Because we haven't received any new information about this issue and the original behavior is no longer a problem in the current release, I'm closing this ticket. @tgg-praveengupta if you'd like to open a new issue with the behavior you're seeing with the dropdown, feel free to do that and we can look into it!

**Closed by sarmeyer** 2018-09-07 16:07 UTC
Labels: unverified
