### ISSUE TITLE
Carousel compressed on initial render until zoom out. 

### ISSUE THREAD

**Issue by robrobkay51** [FormidableLabs/nuka-carousel#191] opened 2017-02-01 22:43 UTC
I'm experiencing a weird situation when using this carousel component: on the initial render, the carousel content is collapsed unnaturally until zooming out, at which point, it displays as expected.

As far as I can see, everything else is working correctly.

How can I correct this issue? Thanks.

**Comment by DavideDaniel** [comment] 2017-02-03 08:12
I believe this might be a duplicate of https://github.com/FormidableLabs/nuka-carousel/issues/103. If it is, the best solution we've found is to dispatch a resize event in image onLoad:

**Comment by DavideDaniel** [comment] 2017-02-04 20:08
@robrobkay51 was the above suggestion helpful?

**Comment by robrobkay51** [comment] 2017-02-04 21:34
@DavideDaniel This works, thanks!

**Comment by DavideDaniel** [comment] 2017-02-05 12:50
Great! @kenwheeler, this issue can be closed.

**Closed** 2017-04-17 15:30 UTC
