### ISSUE TITLE
Slide Height Issues On Load

### ISSUE THREAD

**Issue by erwstout** [FormidableLabs/nuka-carousel#265] opened 2017-11-07 20:27 UTC
This is similar to #219 - but the slider height collapses on load (is `0px`), but if the browser window is resized at all the slider then snaps to the correct height. Example on [CodeSandbox](https://codesandbox.io/s/7joyqwwnpj).

Any thoughts on how to fix or get around this? I'd like to let the slider height by default be the largest slide.

**Comment by thomhos** [comment] 2017-11-09 09:36
Interesting.. I have the same, but the opposite. It's got a height of 1800+ pixels and snaps to the correct height on resize.

**Comment by meganrealtyshares** [comment] 2017-11-13 23:36
I am having a similar issue. The height of the `list-style` loads properly the first time (around 401px as expected), then if the browser is resized to test for mobile, the slide is cut off with the height around 259px -- resizing the window snaps the height back into place. Then, when I resize back to desktop-size, the height is more than double the original with 859px, and resizing the browser slightly snaps it back to 401px.

**Comment by gmattie** [comment] 2017-11-17 16:39
We are also experiencing the same problem.  We have 3 instances of the carousel running on our main page, all of them default to different, incorrect heights when the page is loaded within a responsive state.  As others have already mentioned, resizing the page will force a reflow and fix the issue.  However, this is not possible on a mobile device.

As all of the content we want to show within the carousel instances have a height proportionate to the width, we are bypassing this issue simply by setting a minimum height rule in our stylesheet:

```
.slider-list {
  min-height: calc(100vw + 10rem); 
}
```

**Comment by sunhohong** [comment] 2018-01-22 05:38
Here is a tricky solution for this problem.

Declare the Carousel' ref to get images load event
`
<Carousel ref={c => this.carousel = c} >
  { images.map(image => 
    <img src={image.url} onLoad={this._handleLoadImage} />
  )}
</Carousel>
`
then add handler
`
 _handleLoadImage = () => {
   this.carousel.setDimensions()
 }
`

**Comment by bdefore** [comment] 2018-02-27 14:47
Riffing on @sunhohong 's workaround above, for an approach more agnostic to the children and their incoming props, you can also do:

```
  const sizeAwareChildren = React.Children.map(children, C => {
    return { ...C, props: { ...C.props, onLoad: () => this.carousel.setDimensions() } }
  })
```

...and then remember to set `ref` in the Nuka instance:

```
    <NukaCarousel children={sizeAwareChildren} ref={c => { this.carousel = c }} />
```

Note that there is some discussion and PR's about how to fix this within Nuka itself: https://github.com/FormidableLabs/nuka-carousel/issues/285

**Comment by ryan-roemer** [comment] 2018-03-10 21:12
Is this still an issue on `nuka-carousel@3.1.0+` now that we've landed https://github.com/FormidableLabs/nuka-carousel/pull/291?

**Comment by sr-cjardin** [comment] 2018-03-11 03:09
I am having this issue as well. The default state is loading with a slideHeight of 0 regardless of supplying a initialHeight prop. To reproduce this I am clicking on a link from index.html which loads a details page with the carousel component. On initial loading the height stored in state is "0" if you refresh the page the state will set the height as intended. Navigating back to homepage and into another detail page will also display the carousel as expected upon refreshing or re-sizing the viewport.

**Comment by mbdry** [comment] 2018-03-23 16:58
I still have the issue on 4.0.1. When the carousel is loaded after a request for exemple, the height is 0px, event if the images are in the DOM. If we deactivate the height: 0 in the style tool of chrome, we can see the carousel...

If we resize the page, the image appears !! very weird...

The DOM:
![capture d ecran 2018-03-23 a 17 56 49](https://user-images.githubusercontent.com/32486006/37842853-a187361a-2ec3-11e8-8fa8-e6ce980b1ff4.png)

The style applied to the ul element (with height equal to 0):
![capture d ecran 2018-03-23 a 17 57 02](https://user-images.githubusercontent.com/32486006/37842873-ad5e9bf4-2ec3-11e8-83b9-fd9ed3866777.png)

Any idea ??

Thanks !!

**Comment by karthikmurugadoss** [comment] 2018-03-23 17:56
I'm still facing the issue as well (on 4.0.1). In my case each slide contains a number of divs whose height can vary dynamically. The carousel height does not match the height of the divs (either there is blank space or some content is hidden) which gets adjusted correctly during a resize. Using the following in the parent component housing the carousel seems to resolve it (as mentioned in #103) though.
```
componentDidUpdate() {
    setTimeout(() => {
        window.dispatchEvent(new Event('resize'));
    }, 0);
}
```

**Comment by quantumninja** [comment] 2018-03-27 00:29
Can confirm @karthikmurugadoss code works.

**Comment by bpringe** [comment] 2018-06-12 19:04
I'm having the same issue. Setting `initialSlideHeight` to something non-zero works for me (another workaround for now).

**Comment by bpringe** [comment] 2018-06-12 19:22
I think I see the issue, but I'm not sure exactly how a fix should be implemented. When the component loads initially, `getSlideHeight` is called to get the slideHeight. If the heightMode is set to 'first' (default) then it will set the height to the height of the first slide. However, **if the slides are images that need to load from a URL, and no height is set on the <img> element the height of the first element is unknown (or 0) at the time of the component initially rendering.**

```
getSlideHeight(props, childNodes = []) {
    const { heightMode, vertical } = props;
    const firstSlide = childNodes[0];
    if (firstSlide && heightMode === 'first') {
      return vertical
        ? firstSlide.offsetHeight * props.slidesToShow
        : firstSlide.offsetHeight;
    }
    if (heightMode === 'max') {
      return this.findMaxHeightSlide(childNodes);
    }
    if (props.heightMode === 'current') {
      return childNodes[this.state.currentSlide].offsetHeight;
    }

    return 100;
  }
```
If I set my initial slide element's height attribute then my slides render correctly on initial load.
`<img height="300" src="http://placehold.it/1000x400?text=Slide1" />`

**Comment by nicomfe** [comment] 2018-07-09 03:38
This was working for me:

`componentDidUpdate() {
    setTimeout(() => {
        window.dispatchEvent(new Event('resize'));
    }, 0);
}`

But after updating to version 4.2.5 issue came back.

**Comment by nicomfe** [comment] 2018-08-05 20:46
@larry-dalmeida As I said before adding this componentDidUpdate to the component where you display the carousel fixed the issue for me. 
```
componentDidUpdate() {
    setTimeout(() => {
        window.dispatchEvent(new Event('resize'));
    }, 0);
}
```

BUT after updating to 4.2.5 broke it again, and the same issue is happening

**Comment by maximus-lynn** [comment] 2018-08-14 15:03
Still an issue for me.

**Comment by ryan-roemer** [comment] 2018-08-14 15:17
This PR purported to solve this issue: https://github.com/FormidableLabs/nuka-carousel/pull/305/files

Can someone create a minimal repository with install and error reproduction steps so that we can git clone it and see for ourselves?

**Comment by maximus-lynn** [comment] 2018-08-14 15:18
It did work when I applied the below code as our project gets rendered on  the server:

`  componentDidMount() {
    setTimeout(() => {
      window.dispatchEvent(new Event('resize'));
    }, 0);
  }`

**Comment by ryan-roemer** [comment] 2018-08-14 15:29
Can you create a minimal repository with install + error reproduction steps to show the scenario:

> changing code that is injected into the page.

? Thanks!

**Comment by maximus-lynn** [comment] 2018-08-14 15:33
Sorry I haven't got time to do that. 

However I'd recommend doing a re-render of the component once it has loaded. This way you will get the right height as the images would have loaded onto the page at this point. 

Cheers

**Comment by jakewies** [comment] 2018-08-15 21:39
+1

`slider-list` is 0px `height` on load.

**Comment by mrsamirmh** [comment] 2018-08-28 16:31
+1
Still the same

**Comment by fredrik-sogaard** [comment] 2018-09-01 19:13
I solved it by adding a min-height value on `slider-list` and `slider-frame`. Not ideal, but works.

**Comment by brybrophy** [comment] 2018-09-05 22:25
This is an issue for me as well. Trying to set heightMode to `current` and the only way to get the slide to resize the the correct height is by resizing the window after each slide changes.

**Comment by sarmeyer** [comment] 2018-09-06 19:54
Thanks @brybrophy for this fix!

**Closed by sarmeyer** 2018-09-06 19:54 UTC
Labels: investigate, unverified

**Comment by haugan** [comment] 2018-11-16 12:13
> 
> 
> I'm still facing the issue as well (on 4.0.1). In my case each slide contains a number of divs whose height can vary dynamically. The carousel height does not match the height of the divs (either there is blank space or some content is hidden) which gets adjusted correctly during a resize. Using the following in the parent component housing the carousel seems to resolve it (as discussed in #103) though.
> 
> ```
> componentDidUpdate() {
>     setTimeout(() => {
>         window.dispatchEvent(new Event('resize'));
>     }, 0);
> }
> ```
> 
> Also, the trick mentioned above with setDimensions() didn't work for me.

This works for me, but seemingly not in IE on initial test runs. Got it working in Chrome and Firefox, though!

**Comment by aamorozov** [comment] 2019-02-04 19:05
@karthikmurugadoss's solution worked for me, I needed to change that to fire in `componentDidMount`, but it worked. 🎉

**Comment by laminatefish** [comment] 2019-03-01 09:48
> I'm still facing the issue as well (on 4.0.1). In my case each slide contains a number of divs whose height can vary dynamically. The carousel height does not match the height of the divs (either there is blank space or some content is hidden) which gets adjusted correctly during a resize. Using the following in the parent component housing the carousel seems to resolve it (as discussed in #103) though.
> 
> ```
> componentDidUpdate() {
>     setTimeout(() => {
>         window.dispatchEvent(new Event('resize'));
>     }, 0);
> }
> ```
> Also, the trick mentioned above with setDimensions() didn't work for me.

Life saver. As I just started seeing the resize issue. Couldn't use other solutions, as content is dynamic divs. This worked like a charm, thank you.

**Comment by heaversm** [comment] 2019-06-06 19:17
I would suggest rather than firing a window resize event to use something like:

```
<Carousel 
ref={ref => {
  this.carouselRef = ref;
}}
/>

componentDidMount() {
 setTimeout(() => {
        this.carouselRef.onResize();
    }, 0);
}
```

In my case I already had other events responding to the window resize event, so it forced the carousel into an endless update loop. Switching to an event directed only at the carousel solved this.

**Comment by furkanozalp** [comment] 2019-10-09 06:48
> Here is a tricky solution for this problem.
> 
> Declare the Carousel' ref to get images load event
> 
> ```
> <Carousel ref={c => this.carousel = c} >
>   { images.map(image => 
>     <img src={image.url} onLoad={this._handleLoadImage} />
>   )}
> </Carousel>
> ```
> 
> then add handler
> 
> ```
>  _handleLoadImage = () => {
>    this.carousel.setDimensions()
>  }
> ```

working, thanks for solution

**Comment by lucacaputo** [comment] 2019-11-28 08:41
> Here is a tricky solution for this problem.
> 
> Declare the Carousel' ref to get images load event
> 
> ```
> <Carousel ref={c => this.carousel = c} >
>   { images.map(image => 
>     <img src={image.url} onLoad={this._handleLoadImage} />
>   )}
> </Carousel>
> ```
> 
> then add handler
> 
> ```
>  _handleLoadImage = () => {
>    this.carousel.setDimensions()
>  }
> ```

this one worked for me. i previously had an issue also on initial width, which was fixed with this line here
`.slider>.slider-frame>.slider-list {
    width: auto !important;
}`

also this seems to be an issue with containers having `flex: 1;`.
i  used the `useRef` hook to access the carousel instance.
Thanks
