### ISSUE TITLE
Scroll by x unless not enough slides

### ISSUE THREAD

**Issue by tamagokun** [FormidableLabs/nuka-carousel#13] opened 2015-06-26 11:07 UTC
I have a carousel that shows 4 at a time, and scrolls by 4. Works great.

One issue I ran into is when I have 10 slides so there are 2 sets of 4, then on the last set there are only 2 slides so I have 2 slides on the left, and 2 empty spaces on the right. It would be better if at that point the slider just scrolled 2 slides over rather than 4 and leaving an empty space.

I've used slick a lot in the past and am almost certain it does this, so I was hoping for some guidance on doing this with nuka-carousel.

**Comment by sompylasar** [comment] 2016-02-10 21:56
:+1:

**Comment by sompylasar** [comment] 2016-02-12 00:50
Fixed in #55.

@kenwheeler Please publish this fix to npm.

**Comment by MarinaaaniraM** [comment] 2016-02-22 17:56
Dots don't work fine. Check it...

**Comment by sompylasar** [comment] 2016-02-22 20:39
@MarinaaaniraM you are welcome to suggest a fix.

**Comment by agroves333** [comment] 2016-10-28 16:13
I would like to see this as optional. We use this carousel with pagination. Basically we calculate the page number based on the slidesToShow. 

So, when we have 10 slides, and slidesToShow/slidesToScroll = 4, the last two are for page 3. This fix breaks that since page is still calculated to be 2 with 2 more scrolled over instead of all 4 as we intended (which is dictated by the prop slidesToScroll).

I think we should add an option to toggle this behavior. Thoughts?

**Comment by kenwheeler** [comment] 2016-10-28 16:15
@agroves333 good call, care to PR? Trying to get a release out today at some point.

**Comment by agroves333** [comment] 2016-10-28 16:15
Yes, I'll get in there and see if I can get it rollin' 

Thanks

**Comment by agroves333** [comment] 2016-10-28 18:29
Ken, this feature is ready to be checked in, but I'll need to run test first. Since I'm on MacOS Sierra, this issue will need to be pulled in before I can do it:

https://github.com/FormidableLabs/nuka-carousel/pull/150

**Comment by lauterry** [comment] 2017-07-11 07:49
Hi everyone

is scrollMode props not available yet ?

When will it be published to npm ?

I have the same issue as described by @tamagokun 

Thanks

Best regards

**Comment by lauterry** [comment] 2017-07-23 08:35
Hello

Any update on this issue please ?

Best regards

**Comment by sleeparrow** [comment] 2017-09-14 20:57
@lauterry #249

**Comment by ashika01** [comment] 2018-09-24 23:20
Closing the issue because it has been fixed in a newer version. Please reopen with the issue template if you still experience this issue with the latest stable version.
Thank you.

**Comment by omar-complex** [comment] 2019-01-15 17:20
This issue still exists. I understand that some commits had to be reverted as noted in the linked issue above^ but the scrollMode prop still has not made it into master or in some other form for those that need it. This issue can be reproduced by simply opening the sandbox demo in the repo README and changing `slidesToShow=4` and add `slidesToScroll=4` while keeping `length=6`. https://codesandbox.io/s/94jx21pyvw

**Comment by sarmeyer** [comment] 2020-01-12 00:43
@omar-complex I verified with the newest version (6.0) the issue with the dot highlighting is no longer present. I'm not sure what happened to the `scrollMode` prop, but I'll open a new issue as an enhancement request so it can be triaged and tracked (more easily than in this old ticket at the end of the list).

**Closed by sarmeyer** 2020-01-12 00:43 UTC
